# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='modified',
        ),
        migrations.AddField(
            model_name='contact',
            name='start',
            field=models.DateTimeField(default=None),
        ),
    ]
