# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_auth', '0002_auto_20161010_2357'),
        ('contact', '0003_auto_20161009_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profiles',
            field=models.ManyToManyField(help_text='The (at most two) profiles involved in the contact.', to='pest_auth.Profile'),
        ),
    ]
