# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pest_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="The unique identifier for our user. Since Java's UUID class also follows RFC 4122, there should be no problems using this id on both systems.", primary_key=True, serialize=False),
        ),
    ]
