# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 14:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_auth', '0002_auto_20161010_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='end_sickness',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(default=None), blank=True, default=list, help_text='The time a person stoped being sick.', size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_sickness',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(default=None), blank=True, default=list, help_text='The time a person started being sick.', size=None),
        ),
    ]
